Layout/LineLength:
  Max: 150

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/NumericPredicate:
  AutoCorrect: true

Layout/HashAlignment:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true
